apiVersion: backstage.io/v1alpha1
kind: Component

# Metadata
metadata:
  name: owasp-juice-shop-config
  title: OWASP Juice Shop Configuration

# Specification
spec:
  type: website
  owner: Tahoma Engineers
  lifecycle: production
  system: juice-shop