version: 2.1
workflows:
 wk-1:
  jobs:
    - build
 schedule-workflow:
   triggers:
    - schedule:
        cron: "0 * * * *"
        filters:
          branches:
            only:
             - circleci-project-setup 
   jobs:
    - build
    - deploy
         
jobs:
  build:
    docker:
      - image: cimg/node:22.6.0
    steps:
      - checkout
      - run: 
         name: install dependencies
         command:  npm install

      - run: 
          name: Run Test
          command:  npm run test

  deploy: 
    docker: 
      - image: circleci/node
    working_directory: ~/circleci-demo-schedule
    steps: 
      - checkout 
      - run:
          name: Run deploy Command
          command: echo "hello i am deploying"
