version: 2.1
workflows:
 wk-1:
  jobs:
    - build
jobs:
  build:
    docker:
      - image: cimg/node:22.6.0
    steps:
      - checkout
      - run: 
         name: install dependencies
         command:  npm install

      - run: 
          name: Run Test
          command:  npm run test
         
