version: 2.1
workflows:
  semgrep:
    jobs:
      - semgrep-full-scan:
          filters:
            branches:
              only: circleci-project-setup
          context:
            - semgrep
jobs:
  semgrep-full-scan:
    docker:
      - image: semgrep/semgrep
    steps:
      - checkout
      - run:
          name: "Semgrep OSS full scan"
          command: semgrep --config=local-config.yml --metrics=off
