name: Snyk - Webinar
on: workflow_dispatch #push #pull_request
jobs:
  configure:
    runs-on: ubuntu-latest
    steps:
      - name: Configure
        run: echo configure
  checkout:
    needs: configure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Checkout
        run: echo checkout
  build:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install npm
        run: echo install
  security_gate_snyk_opec_source:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install npm
        run: npm install
      - name: Run Snyk Open-Source
        uses: snyk/actions/node@master
        continue-on-error: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: test
          args: --sarif-file-output=snyk_sca.sarif --severity-threshold=high
          
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_sca.sarif
  security_gate_snyk_code:
    needs: [security_gate_snyk_opec_source]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk Code
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: --sarif-file-output=snyk_code.sarif --severity-threshold=high
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk_code.sarif
  snyk_monitoring:
    needs: security_gate_snyk_opec_source
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Apply Snyk monitor
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: monitor
